development:
  adapter: postgresql
  encoding: utf8
  database: cleanspeech_development
  pool: 5
  timeout: 5000
 

test: &TEST
  adapter: sqlite3
  encoding: utf8
  database: cleanspeech_test
  pool: 5
  timeout: 5000
 

production:
  adapter: postgresql
  encoding: utf8
  database: cleanspeech_production
  pool: 5
  timeout: 5000
 

